spring:
  profiles:
  #'@spring.profiles.active@'
    active: '@spring.profiles.active@'
#jackson相关配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #时区必须要设置
    time-zone: GMT+8
    #ALWAYS的意思是即时属性为null，仍然也会输出这个key
    default-property-inclusion: ALWAYS
    serialization:
      indent-output: true